/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markus.ginrummy.kayttoliittyma;

import java.awt.Color;
import java.awt.Graphics;
import markus.ginrummy.logiikka.Card;
import markus.ginrummy.logiikka.Client;
import markus.ginrummy.logiikka.Suit;

/**
 *
 * @author Markus
 */
public class PlayingCard extends javax.swing.JPanel {
    
    private Card card;
    private String suit;
    private String value;
    private Client client;
    private int idx;
    private Color color;

    /**
     * Creates new form PalyingCard
     */
    public PlayingCard(Card card, Client client, int idx) {
        initComponents();
        this.card = card;
        if (card.getSuit().equals(Suit.HERTTA)) {
            suit = "\u2665";
            color = Color.RED;
        } else if (card.getSuit().equals(Suit.PATA)) {
            suit = "\u2660";
            color = Color.BLACK;
        } else if (card.getSuit().equals(Suit.RISTI)) {
            suit = "\u2663";
            color = Color.BLACK;
        } else {
            suit = "\u2666";
            color = Color.RED;
        }
        value = card.valueString();
        this.client = client;
        this.idx = idx;
    }

    public PlayingCard(Card card, Client client) {
        initComponents();
        this.card = card;
        if (card.getSuit().equals(Suit.HERTTA)) {
            suit = "\u2665";
            color = Color.RED;
        } else if (card.getSuit().equals(Suit.PATA)) {
            suit = "\u2660";
            color = Color.BLACK;
        } else if (card.getSuit().equals(Suit.RISTI)) {
            suit = "\u2663";
            color = Color.BLACK;
        } else {
            suit = "\u2666";
            color = Color.RED;
        }
        value = card.valueString();
        this.client = client;
        idx = 99;
    }    
    
    

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.setFont(g.getFont().deriveFont(50f));
        g.setColor(color);
        g.drawString(value, 14, 50);
        g.drawString(suit, 10, 100);
        g.setFont(g.getFont().deriveFont(150f));
        g.drawString(suit, this.getWidth()/2 - 65, this.getHeight()/2 + 55);      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(200, 280));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (idx != 99) {
            client.print("/" + idx);
        } else {
            client.print("/1");
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
